#pragma once

#include "defs.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>

#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "ZXelerator.pio.h" // autogenerated
#include "myTypes.h"
#include "shared.h"

// Used by game
extern MemoryBank ram[2];
extern volatile int flipBank;
//extern volatile int frameOver;
extern uint32_t readBank, writeBank;

void setupIO(void);
void releaseReset(void);
void handleZ80Read(void);
void resetButton(uint gpio,uint32_t events);
void copyBank(MemoryBank *dest, const MemoryBank *src);

void enableROMOutput(void);
