#pragma once

#include "defs.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>

#include "hardware/sync.h"
#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "ZXelerator.pio.h" // autogenerated
#include "myTypes.h"
#include "shared.h"

void setupIO(void);
void setupPIO(void);
void releaseReset(void);
void handleZ80Read(void);
void resetButton(uint gpio,uint32_t events);
void copyBank(MemoryBank *dest, const MemoryBank *src);
void copyBankSafe(MemoryBank *dest, const MemoryBank *src);
void testBlit(void);
void enableROMOutput(void);
