#pragma once

#include <stdint.h>

// The engine's tile sets (every 4096 byte array declared in engine/tileDefs.h), by name, so the level converter can
// draw them for Tiled. Generated by pc/CMakeLists.txt
typedef struct TileSetEntry {
    const char *name;
    const uint8_t *tiles;
    int size;           // 4096 for 8x8 tiles, 16384 for 16x16
} TileSetEntry;

extern const TileSetEntry tileSetRegistry[];

// The engine's sprite graphics and masks (every array declared in engine/spriteDefs.h), with their sizes
typedef struct SpriteDefEntry {
    const char *name;
    const uint8_t *data;
    int size;
} SpriteDefEntry;

extern const SpriteDefEntry spriteDefRegistry[];
