// Generated by levelconv from cave.tmx - edit the level in Tiled and convert it again, rather than editing this

#include <stddef.h>
#include "level.h"
#include "tileDefs.h"
#include "spriteDefs.h"
#include "levelObjects.h"
#include "tileset_demoTiles.h"

// Layer "Back": 48x24 tiles from 0,0, 0 foreground tiles - 1152 bytes packed to 9
static const uint8_t layer0Data[9]={
    0x1F,0x18,0x01,0x00,0xFF,0xFF,0xFF,0xFF,0x70,
};

// Layer "Level": 48x24 tiles from 0,0, 0 foreground tiles - 1152 bytes packed to 69
static const uint8_t layer1Data[69]={
    0x1F,0x03,0x01,0x00,0x4E,0x1F,0x00,0x01,0x00,0x18,0x0F,0x30,0x00,0xFB,0x14,0x1E,0x08,0x00,0x0F,0x30,0x00,0x14,0x05,0x73,
    0x01,0x0F,0x30,0x00,0x0D,0x3F,0x0C,0x0C,0x0C,0x20,0x01,0x49,0x10,0x06,0x01,0x00,0x0F,0x60,0x00,0x41,0x07,0xB8,0x00,0x0F,
    0xC0,0x00,0x41,0x0B,0xB8,0x00,0x0E,0x60,0x00,0x0F,0xA0,0x02,0x82,0x0F,0xBC,0x03,0x0A,0x0F,0x01,0x00,0x8E,
};

// Tile sets (shared with other levels using them)
static const LevelTileSet *const tileSets[]={
    &tileSet_demoTiles,
};

static const LevelLayer layers[]={
    {layer0Data,9,48,24,0,0,0,0,256,256,0,0,0,4,-1,0,"Back",0,0x00},
    {layer1Data,69,48,24,0,0,0,0,256,256,0,0,0,2,-1,0,"Level",0,0x00},
};

// Sprite sheets
static const LevelSpriteSheet sheets[]={
    {exitDoorDef,exitDoorMaskDef,15,11,4,0},      // "exitDoor" (SIZE_16X32)
    {keyDef,keyMaskDef,4,6,1,0},      // "key" (SIZE_16X8)
};

// Objects' properties and paths
static const LevelProp object1Props[]={{LEVEL_PROP_TO_LEVEL,LEVEL_PROP_TYPE_INT,{.i=1}},{LEVEL_PROP_TO_ENTRANCE,LEVEL_PROP_TYPE_STRING,{.s="cave door"}}};
static const LevelProp object2Props[]={{LEVEL_PROP_VALUE,LEVEL_PROP_TYPE_INT,{.i=2}},{LEVEL_PROP_PERSIST,LEVEL_PROP_TYPE_INT,{.i=1}}};
static const LevelProp object3Props[]={{LEVEL_PROP_TO_LEVEL,LEVEL_PROP_TYPE_INT,{.i=2}},{LEVEL_PROP_TO_ENTRANCE,LEVEL_PROP_TYPE_STRING,{.s="from cave"}}};

static const LevelObject objects[]={
    {LEVEL_CLASS_ENTRANCE,-1,0,0x00,2,0,0,60,149,0,0,NULL,NULL,"from demo",-1,0,0,0,0},    // 0: Tiled object 1
    {LEVEL_CLASS_EXIT,0,0,0x00,2,2,0,40,144,16,32,object1Props,NULL,"to demo",-1,0,0,0,0},    // 1: Tiled object 2
    {LEVEL_CLASS_KEY,1,0,0x10,2,2,0,256,68,16,8,object2Props,NULL,"door key",0,2,0,0,0},    // 2: Tiled object 3
    {LEVEL_CLASS_EXIT,0,0,0x00,2,2,0,344,144,16,32,object3Props,NULL,"to demo16",-1,0,0,0,0},    // 3: Tiled object 4
    {LEVEL_CLASS_ENTRANCE,-1,0,0x00,2,0,0,344,149,0,0,NULL,NULL,"from demo16",-1,0,0,0,0},    // 4: Tiled object 5
};

// The level's own properties
static const LevelProp levelProps[]={{LEVEL_PROP_LEVEL_TYPE,LEVEL_PROP_TYPE_INT,{.i=0}},{LEVEL_PROP_LEVEL_NAME,LEVEL_PROP_TYPE_STRING,{.s="The Cave"}},{LEVEL_PROP_LEVEL_DESCRIPTION,LEVEL_PROP_TYPE_STRING,{.s="Find the key to the locked door"}}};

const LevelDef level_cave={"cave",48,24,6560,1,2,2,5,tileSets,layers,sheets,objects,0,1,8,levelProps,3,0};
