// Generated by levelconv - every level, numbered by the order of their maps' names (levelList in engine/level.h)
#pragma once

#include "level.h"
#include "levelObjects.h"
#include "level_cave.h"
#include "level_demo.h"

#define LEVEL_ID_CAVE                     0
#define LEVEL_ID_DEMO                     1
#define LEVEL_COUNT                       2
