// Generated by levelconv from demo
#pragma once

#include "level.h"

extern const LevelDef level_demo;

// Remembered objects' slots (setLevelSwitchState)
#define LEVEL_SLOT_DEMO_PISTON_LEVER 0
#define LEVEL_SLOT_DEMO_TREASURE_DOOR 1
