// Generated by levelconv from the Tiled project (levels/tiled/ZXelerator.tiled-project) - the object classes and their properties set up
// there, numbered for LevelObject's cls and the getLevelObject... functions
#pragma once

#define LEVEL_CLASS_NONE                0
#define LEVEL_CLASS_PLAYER_START         1
#define LEVEL_CLASS_ENEMY                2
#define LEVEL_CLASS_PLATFORM             3
#define LEVEL_CLASS_GENERATOR            4
#define LEVEL_CLASS_PISTON               5
#define LEVEL_CLASS_SWITCH               6
#define LEVEL_CLASS_KEY                  7
#define LEVEL_CLASS_DOOR                 8
#define LEVEL_CLASS_ENTRANCE             9
#define LEVEL_CLASS_EXIT                 10
#define LEVEL_CLASS_COUNT               11

#define LEVEL_PROP_SPEED                 0
#define LEVEL_PROP_CHASE_SPEED           1
#define LEVEL_PROP_ALERT_RANGE           2
#define LEVEL_PROP_WAIT_FOR_CAMERA       3
#define LEVEL_PROP_PATH                  4
#define LEVEL_PROP_INTERVAL              5
#define LEVEL_PROP_MAX                   6
#define LEVEL_PROP_SPEED_OUT             7
#define LEVEL_PROP_SPEED_IN              8
#define LEVEL_PROP_WAIT_OUT              9
#define LEVEL_PROP_WAIT_IN               10
#define LEVEL_PROP_PHASE                 11
#define LEVEL_PROP_SHAFT_TILE            12
#define LEVEL_PROP_VALUE                 13
#define LEVEL_PROP_MODE                  14
#define LEVEL_PROP_TIME                  15
#define LEVEL_PROP_START_ON              16
#define LEVEL_PROP_PERSIST               17
#define LEVEL_PROP_TO_LEVEL              18
#define LEVEL_PROP_TO_ENTRANCE           19

// ZXColour
#define ZXCOLOUR_BLACK                   0
#define ZXCOLOUR_BLUE                    1
#define ZXCOLOUR_RED                     2
#define ZXCOLOUR_MAGENTA                 3
#define ZXCOLOUR_GREEN                   4
#define ZXCOLOUR_CYAN                    5
#define ZXCOLOUR_YELLOW                  6
#define ZXCOLOUR_WHITE                   7
#define ZXCOLOUR_COUNT 8

// SwitchMode
#define SWITCH_MODE_ONCE                 0
#define SWITCH_MODE_TOGGLE               1
#define SWITCH_MODE_TIMED                2
#define SWITCH_MODE_COUNT 3

// SwitchId
#define SWITCH_ID_PISTONS                0
#define SWITCH_ID_LIFT_CALL              1
#define SWITCH_ID_DOOR_A                 2
#define SWITCH_ID_COUNT 3
