// Generated by levelconv - every level, by LEVEL_ID_...
#include <stddef.h>
#include "levels.h"

const LevelDef *const levelList[4]={
    &level_cave,
    &level_demo,
    &level_demo16,
    &level_flight,
};
const int levelCount=4;
