#pragma once

#include <stdint.h>
#include <stdbool.h>
#include "defs.h"
#include "shared.h"

// The ASM template contains two lists of "out (c),d" / "out (c),e" instructions that drive the beeper.
// D=0x00 (speaker off), E=0x10 (speaker on), so each entry is ED 51 (off) or ED 59 (on), and only the
// second byte needs to change. Each OUT takes 12 T-states, so each entry is one ~291.7kHz 1-bit sample.
//
// Within a frame (2 TV frames, 139776 T-states) the lists play:
//   samples 0-502      sub-bank 0, just after the HALT (top border of the first TV frame)
//   samples 503-1352   sub-bank 1, at the end of the second TV frame, just before the next HALT
// So sample 1352 of one frame is followed (after a short gap for the HALT/interrupt) by sample 0 of the next.
//
// Offsets/lengths must match the template generated by code/ASM/push_map.html (addAudioList calls)

#define AUDIO_LIST0_OFFSET      0x00ce  // In sub-bank 0
#define AUDIO_LIST0_LEN         503
#define AUDIO_LIST1_OFFSET      0x2817  // In sub-bank 1
#define AUDIO_LIST1_LEN         850
#define AUDIO_SAMPLES_PER_FRAME (AUDIO_LIST0_LEN+AUDIO_LIST1_LEN)
#define AUDIO_TSTATES_PER_SAMPLE 12

#define AUDIO_OUT_OFF           0x51    // out (c),d
#define AUDIO_OUT_ON            0x59    // out (c),e

/// @brief Set a single beeper sample in the frame currently being generated (the write bank).
/// Note the write bank still holds the audio from 2 frames ago, so every sample should be written each
/// frame (use clearAudio() first if only setting some of them)
/// @param ix Sample index, 0 to AUDIO_SAMPLES_PER_FRAME-1 (out of range indexes are ignored)
/// @param on True to set the speaker on for this sample
void setAudioBit(int ix, bool on);

/// @brief Set every beeper sample in the frame currently being generated to off
void clearAudio(void);

/// @brief Read back a beeper sample from an ASM bank
/// @param bankIX The ram bank to read from
/// @param ix Sample index, 0 to AUDIO_SAMPLES_PER_FRAME-1
/// @return True if the speaker is on for this sample
bool getAudioBit(int bankIX, int ix);
